backend-mvc5/Angle/Angle/Controllers/PagesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Angle.Controllers
{
    public class PagesController : Controller
    {
        public ActionResult Error_404()
        {
            return View();
        }
        public ActionResult Lock() {
            return View();
        }
        public ActionResult Login() {
            return View();
        }
        public ActionResult Recover() {
            return View();
        }
        public ActionResult Register() {
            return View();
        }
        public ActionResult Template()
        {
            return View();
        }
    }
}

backend-mvc5/Angle/Angle/Views/Shared/_Footer.cshtml
<span>&copy; 2015 - Angle</span>

backend-mvc5/Angle/Angle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="Bootstrap Admin App + jQuery">
    <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
    <title>Angle - Bootstrap Admin Template</title>
    <!-- =============== VENDOR STYLES ===============-->
    @Styles.Render("~/bundles/fontawesome")
    @Styles.Render("~/bundles/simpleLineIcons")
    @Styles.Render("~/bundles/animatecss")
    @Styles.Render("~/bundles/whirl")
    <!-- =============== PAGE VENDOR STYLES =============== -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
    <!-- =============== APP STYLES ===============-->
    <link href="@Styles.Url("~/Content/app/css/app.css")" rel="stylesheet" type="text/css" id="maincss" />

</head>
<body>
    <div class="wrapper">
        <!-- top navbar-->
        <header class="topnavbar-wrapper">
            @Html.Partial("_TopNavbar")
        </header>
        <!-- sidebar-->
        <aside class="aside">
            @Html.Partial("_Sidebar")
        </aside>
        <!-- offsidebar-->
        <aside class="offsidebar">
            @Html.Partial("_Offsidebar")
        </aside>
        <!-- Main section-->
        <section>
            <!-- Page content-->
            <div class="content-wrapper">
                @RenderBody()
            </div>
        </section>
        <!-- Page footer-->
        <footer>
            @Html.Partial("_Footer")
        </footer>
    </div>
    <!-- =============== VENDOR SCRIPTS ===============-->
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/storage")
    @Scripts.Render("~/bundles/jquery.easing")
    @Scripts.Render("~/bundles/animo")
    @Scripts.Render("~/bundles/slimscroll")
    @Scripts.Render("~/bundles/screenfull")
    @Scripts.Render("~/bundles/localize")
    @Scripts.Render("~/bundles/demoRTL")
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    @RenderSection("scripts", required: false)
    <!-- =============== APP SCRIPTS ===============-->
    @Scripts.Render("~/bundles/Angle")
</body>
</html>

backend-mvc5/Angle/Angle/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
   <meta name="description" content="Bootstrap Admin App + jQuery">
   <meta name="keywords" content="app, responsive, jquery, bootstrap, dashboard, admin">
   <title>Angle - Bootstrap Admin Template</title>
    <!-- =============== VENDOR STYLES ===============-->
    @Styles.Render("~/bundles/fontawesome")
    @Styles.Render("~/bundles/simpleLineIcons")
    <!-- =============== PAGE VENDOR STYLES =============== -->
    @if (IsSectionDefined("Styles"))
        {@RenderSection("Styles", required: false)}
    <!-- =============== APP STYLES ===============-->
    @Styles.Render("~/Content/css")
</head>

<body>
   <div class="wrapper">
       @RenderBody()
   </div>
   <div class="p-lg text-center">
      <span>&copy;</span>
      <span>2015</span>
      <span>-</span>
      <span>Angle</span>
      <br>
      <span>Bootstrap Admin Template</span>
   </div>

    <!-- =============== VENDOR SCRIPTS ===============-->
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/storage")
    @Scripts.Render("~/bundles/parsley")
    <!-- =============== PAGE VENDOR SCRIPTS ===============-->
    @RenderSection("scripts", required: false)
    <!-- =============== APP SCRIPTS ===============-->
    @Scripts.Render("~/bundles/Angle")

</body>

</html>

backend-mvc5/Angle/Angle/Views/Shared/_TopNavbar.cshtml
<!-- START Top Navbar-->
<nav role="navigation" class="navbar topnavbar">
   <!-- START navbar header-->
   <div class="navbar-header">
      <a href="#/" class="navbar-brand">
         <div class="brand-logo">
            <img src="~/Content/Images/logo.png" alt="App Logo" class="img-responsive" />
         </div>
         <div class="brand-logo-collapsed">
             <img src="~/Content/Images/logo-single.png" alt="App Logo" class="img-responsive" />
         </div>
      </a>
   </div>
   <!-- END navbar header-->
   <!-- START Nav wrapper-->
   <div class="nav-wrapper">
      <!-- START Left navbar-->
      <ul class="nav navbar-nav">
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a href="#" data-toggle-state="aside-collapsed" class="hidden-xs">
               <em class="fa fa-navicon"></em>
            </a>
            <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
            <a href="#" data-toggle-state="aside-toggled" data-no-persist="true" class="visible-xs sidebar-toggle">
               <em class="fa fa-navicon"></em>
            </a>
         </li>
         <!-- START User avatar toggle-->
         <li>
            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
            <a href="#user-block" data-toggle="collapse">
               <em class="icon-user"></em>
            </a>
         </li>
         <!-- END User avatar toggle-->
         <!-- START lock screen-->
         <li>
             <a href="@Url.Action("Lock", "Pages")" title="Lock screen">
                 <em class="icon-lock"></em>
             </a>
         </li>
         <!-- END lock screen-->
      </ul>
      <!-- END Left navbar-->
      <!-- START Right Navbar-->
      <ul class="nav navbar-nav navbar-right">
         <!-- Search icon-->
         <li>
            <a href="#" data-search-open="">
               <em class="icon-magnifier"></em>
            </a>
         </li>
         <!-- Fullscreen (only desktops)-->
         <li class="visible-lg">
            <a href="#" data-toggle-fullscreen="">
               <em class="fa fa-expand"></em>
            </a>
         </li>
         <!-- START Alert menu-->
         <li class="dropdown dropdown-list">
            <a href="#" data-toggle="dropdown">
               <em class="icon-bell"></em>
               <div class="label label-danger">11</div>
            </a>
            <!-- START Dropdown menu-->
            <ul class="dropdown-menu animated flipInX">
               <li>
                  <!-- START list group-->
                  <div class="list-group">
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-twitter fa-2x text-info"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New followers</p>
                              <p class="m0 text-muted">
                                 <small>1 new follower</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-envelope fa-2x text-warning"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">New e-mails</p>
                              <p class="m0 text-muted">
                                 <small>You have 10 new emails</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- list item-->
                     <a href="#" class="list-group-item">
                        <div class="media-box">
                           <div class="pull-left">
                              <em class="fa fa-tasks fa-2x text-success"></em>
                           </div>
                           <div class="media-box-body clearfix">
                              <p class="m0">Pending Tasks</p>
                              <p class="m0 text-muted">
                                 <small>11 pending task</small>
                              </p>
                           </div>
                        </div>
                     </a>
                     <!-- last list item -->
                     <a href="#" class="list-group-item">
                        <small>More notifications</small>
                        <span class="label label-danger pull-right">14</span>
                     </a>
                  </div>
                  <!-- END list group-->
               </li>
            </ul>
            <!-- END Dropdown menu-->
         </li>
         <!-- END Alert menu-->
         <!-- START Contacts button-->
         <li>
            <a href="#" data-toggle-state="offsidebar-open" data-no-persist="true">
               <em class="icon-notebook"></em>
            </a>
         </li>
         <!-- END Contacts menu-->
      </ul>
      <!-- END Right Navbar-->
   </div>
   <!-- END Nav wrapper-->
   <!-- START Search form-->
   <form role="search" action="search.html" class="navbar-form">
      <div class="form-group has-feedback">
         <input type="text" placeholder="Type and hit enter ..." class="form-control" />
         <div data-search-dismiss="" class="fa fa-times form-control-feedback"></div>
      </div>
      <button type="submit" class="hidden btn btn-default">Submit</button>
   </form>
   <!-- END Search form-->
</nav>
<!-- END Top Navbar-->